# -*- coding: utf-8 -*-
"""PlantVillage_Projeto_Final_COMENTADO_ENUMERADO.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10tORLsifNA1WixK31RFacyIz-GWenof1
"""

# CÉLULA 1 — INSTALAÇÃO
!pip -q install -U datasets huggingface_hub scikit-learn seaborn

# Mantém a estratificação das classes e separa grupos de folhas para reduzir vazamento.
# Divisão estratificada mantendo grupos de folhas separados entre treino e teste.
# CÉLULA 2 — IMPORTAÇÕES
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from PIL import Image
from datasets import load_dataset
from sklearn.model_selection import StratifiedGroupKFold, GridSearchCV
from sklearn.preprocessing import LabelEncoder, label_binarize
from sklearn.decomposition import PCA
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.svm import SVC
from sklearn.metrics import (
    accuracy_score, precision_score, recall_score, f1_score,
    classification_report, confusion_matrix, roc_curve, auc
)
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

print("TensorFlow:", tf.__version__)

# CÉLULA 3 — DATASET ONLINE
DATASET_NAME = "geraldmc/plantvillage-full"

print("="*60)
print("PLANTVILLAGE — STREAMING ONLINE")
print("="*60)
print("Fonte:", DATASET_NAME)
print("Modo: streaming")

dataset = load_dataset(
    DATASET_NAME,
    revision="v0.1.0",
    split="train",
    streaming=True
)

primeiro = next(iter(dataset))
print("\nCampos disponíveis:", list(primeiro.keys()))
print("Classe:", primeiro["class_label"])

# CÉLULA 4 — CLASSES
CLASSES_DESEJADAS = [
    "Pepper,_bell___Bacterial_spot",
    "Pepper,_bell___healthy",
    "Potato___Early_blight",
    "Potato___Late_blight",
    "Potato___healthy",
    "Tomato___healthy"
]
MAX_IMAGES_PER_CLASS = 150

for i, classe in enumerate(CLASSES_DESEJADAS, 1):
    print(f"{i}. {classe}")
print("Total esperado:", len(CLASSES_DESEJADAS) * MAX_IMAGES_PER_CLASS)

# CÉLULA 5 — SELEÇÃO BALANCEADA
imagens_por_classe = {classe: [] for classe in CLASSES_DESEJADAS}
contador_total = 0

for exemplo in dataset:
    classe = exemplo.get("class_label")
    if classe not in CLASSES_DESEJADAS:
        continue
    if len(imagens_por_classe[classe]) >= MAX_IMAGES_PER_CLASS:
        continue

    imagem = exemplo.get("image")
    leaf_id = exemplo.get("leaf_id")

    if imagem is None:
        continue

    try:
        imagem = imagem.convert("RGB")
    except Exception:
        continue

    imagens_por_classe[classe].append({
        "image": imagem,
        "leaf_id": leaf_id
    })

    contador_total += 1

    if contador_total % 100 == 0:
        print("Imagens coletadas:", contador_total)

    if all(
        len(imagens_por_classe[c]) >= MAX_IMAGES_PER_CLASS
        for c in CLASSES_DESEJADAS
    ):
        break

imagens_selecionadas = []

for classe in CLASSES_DESEJADAS:
    quantidade = len(imagens_por_classe[classe])
    print(f"{classe}: {quantidade}")

    for item in imagens_por_classe[classe]:
        imagens_selecionadas.append({
            "image": item["image"],
            "label": classe,
            "leaf_id": item["leaf_id"]
        })

print("Total:", len(imagens_selecionadas))

if not imagens_selecionadas:
    raise RuntimeError("Nenhuma imagem foi selecionada.")

# CÉLULA 6 — CARREGAMENTO E NORMALIZAÇÃO
IMG_SIZE = (64, 64)

X = []
y_text = []
groups = []

for item in imagens_selecionadas:
    try:
        imagem = item["image"].resize(IMG_SIZE)
        arr = np.array(imagem, dtype=np.float32) / 255.0

        X.append(arr)
        y_text.append(item["label"])
        groups.append(item["leaf_id"])

    except Exception as erro:
        print("Erro:", erro)

X = np.array(X, dtype=np.float32)
y_text = np.array(y_text)
groups = np.array(groups)

print("Dimensão de X:", X.shape)
print("Dimensão de y:", y_text.shape)
print("Quantidade de grupos/folhas:", len(np.unique(groups)))
print("Valores ausentes em X:", np.isnan(X).sum())

# CÉLULA 7 — VISUALIZAÇÃO
plt.figure(figsize=(12, 8))
indices = np.random.choice(len(X), min(12, len(X)), replace=False)

for pos, indice in enumerate(indices):
    plt.subplot(3, 4, pos + 1)
    plt.imshow(X[indice])
    plt.title(y_text[indice], fontsize=8)
    plt.axis("off")

plt.tight_layout()
plt.show()

# CÉLULA 8 — EDA
distribuicao = pd.Series(y_text).value_counts()
quantidades = [distribuicao.get(c, 0) for c in CLASSES_DESEJADAS]

print("Distribuição:")
for c, q in zip(CLASSES_DESEJADAS, quantidades):
    print(c, ":", q)

print("\nNaN:", np.isnan(X).sum())
print("Dimensão:", X.shape[1:])
print("Mínimo:", X.min(), "Máximo:", X.max())

plt.figure(figsize=(12, 6))
plt.bar(CLASSES_DESEJADAS, quantidades)
plt.title("Distribuição das imagens por classe")
plt.xlabel("Classe")
plt.ylabel("Quantidade")
plt.xticks(rotation=30, ha="right")
plt.tight_layout()
plt.show()

# CÉLULA 9 — NOMES PARA VISUALIZAÇÃO
nomes_classes_pt = {
    "Pepper,_bell___Bacterial_spot": "Pimentão — Mancha bacteriana",
    "Pepper,_bell___healthy": "Pimentão — Saudável",
    "Potato___Early_blight": "Batata — Requeima precoce",
    "Potato___Late_blight": "Batata — Requeima tardia",
    "Potato___healthy": "Batata — Saudável",
    "Tomato___healthy": "Tomate — Saudável"
}

# CÉLULA 10 — CODIFICAÇÃO
encoder = LabelEncoder()
y = encoder.fit_transform(y_text)

for i, classe in enumerate(encoder.classes_):
    print(i, "→", nomes_classes_pt[classe])

# Mantém a estratificação das classes e separa grupos de folhas para reduzir vazamento.
# Divisão estratificada mantendo grupos de folhas separados entre treino e teste.
# CÉLULA 11 — TREINO/TESTE SEM VAZAMENTO DE DADOS
# As imagens da mesma folha não podem aparecer simultaneamente
# nos conjuntos de treino e teste.

sgkf = StratifiedGroupKFold(
    n_splits=5,
    shuffle=True,
    random_state=42
)

train_idx, test_idx = next(
    sgkf.split(X, y, groups=groups)
)

X_train_img = X[train_idx]
X_test_img = X[test_idx]
y_train = y[train_idx]
y_test = y[test_idx]

groups_train = groups[train_idx]
groups_test = groups[test_idx]

print("Treino:", X_train_img.shape)
print("Teste:", X_test_img.shape)
print("Folhas no treino:", len(np.unique(groups_train)))
print("Folhas no teste:", len(np.unique(groups_test)))
print(
    "Folhas compartilhadas entre treino e teste:",
    len(set(groups_train) & set(groups_test))
)

# CÉLULA 12 — FLATTEN
X_train_flat = X_train_img.reshape(X_train_img.shape[0], -1)
X_test_flat = X_test_img.reshape(X_test_img.shape[0], -1)

print(X_train_flat.shape, X_test_flat.shape)

# Redução de dimensionalidade da representação das imagens.
# Reduz a dimensionalidade da representação das imagens.
# CÉLULA 13 — PCA
max_pca = min(X_train_flat.shape[0] - 1, X_train_flat.shape[1])
N_COMPONENTES_PCA = min(100, max_pca)

pca = PCA(
    n_components=N_COMPONENTES_PCA,
    whiten=True,
    random_state=42
)

X_train_pca = pca.fit_transform(X_train_flat)
X_test_pca = pca.transform(X_test_flat)

print("Dimensão original:", X_train_flat.shape[1])
print("Após PCA:", X_train_pca.shape[1])
print(
    "Variância explicada:",
    f"{pca.explained_variance_ratio_.sum()*100:.2f}%"
)

# Redução de dimensionalidade da representação das imagens.
# Reduz a dimensionalidade da representação das imagens.
# CÉLULA 14 — PCA 2D
pca_2d = PCA(n_components=2, random_state=42)
X_train_pca_2d = pca_2d.fit_transform(X_train_flat)

plt.figure(figsize=(10, 7))
for classe_id in np.unique(y_train):
    idx = y_train == classe_id
    nome_original = encoder.inverse_transform([classe_id])[0]
    plt.scatter(X_train_pca_2d[idx, 0], X_train_pca_2d[idx, 1],
                label=nomes_classes_pt[nome_original], alpha=0.7)

plt.title("Visualização das classes após PCA")
plt.xlabel("Componente Principal 1")
plt.ylabel("Componente Principal 2")
plt.legend(bbox_to_anchor=(1.05, 1), loc="upper left")
plt.tight_layout()
plt.show()

# CÉLULA 15 — LDA
N_COMPONENTES_LDA = min(
    len(np.unique(y_train)) - 1,
    X_train_pca.shape[1]
)

lda = LinearDiscriminantAnalysis(
    n_components=N_COMPONENTES_LDA
)

X_train_lda = lda.fit_transform(X_train_pca, y_train)
X_test_lda = lda.transform(X_test_pca)

print("Componentes LDA:", N_COMPONENTES_LDA)
print("Treino:", X_train_lda.shape)
print("Teste:", X_test_lda.shape)

# Mantém a estratificação das classes e separa grupos de folhas para reduzir vazamento.
# Divisão estratificada mantendo grupos de folhas separados entre treino e teste.
# ============================================================
# CÉLULA 16 — GRIDSEARCHCV + SVM
# ============================================================

from sklearn.model_selection import StratifiedGroupKFold, GridSearchCV
from sklearn.svm import SVC

param_grid = {
    "C": [0.1, 1, 10],
    "kernel": ["linear", "rbf"],
    "gamma": ["scale", "auto"]
}

cv = StratifiedGroupKFold(
    n_splits=3,
    shuffle=True,
    random_state=42
)

grid_svm = GridSearchCV(
    estimator=SVC(
        probability=True,   # IMPORTANTE PARA predict_proba()
        random_state=42
    ),
    param_grid=param_grid,
    cv=cv,
    scoring="f1_macro",
    n_jobs=-1,
    verbose=1
)

grid_svm.fit(
    X_train_pca,
    y_train,
    groups=groups_train
)

print("\n============================================================")
print("MELHORES PARÂMETROS — SVM")
print("============================================================")

print("Melhores parâmetros:")
print(grid_svm.best_params_)

print("\nMelhor F1-Score médio:")
print(f"{grid_svm.best_score_:.4f}")

modelo_svm = grid_svm.best_estimator_

print("\nModelo SVM selecionado:")
print(modelo_svm)

# CÉLULA 17 — AVALIAÇÃO SVM
svm_pca = grid_svm.best_estimator_
y_pred_svm = svm_pca.predict(X_test_pca)

accuracy_svm = accuracy_score(y_test, y_pred_svm)
precision_svm = precision_score(y_test, y_pred_svm, average="weighted", zero_division=0)
recall_svm = recall_score(y_test, y_pred_svm, average="weighted", zero_division=0)
f1_svm = f1_score(y_test, y_pred_svm, average="weighted", zero_division=0)

print(f"Accuracy : {accuracy_svm:.4f}")
print(f"Precision: {precision_svm:.4f}")
print(f"Recall   : {recall_svm:.4f}")
print(f"F1-Score : {f1_svm:.4f}")

print(classification_report(
    y_test, y_pred_svm,
    target_names=[nomes_classes_pt[c] for c in encoder.classes_],
    zero_division=0
))

# SVM utilizado como modelo supervisionado obrigatório.
# SVM para classificação multiclasse.
# CÉLULA 18 — SVM + PCA + LDA
svm_lda = SVC(C=1, kernel="rbf", gamma="scale", probability=True, random_state=42)
svm_lda.fit(X_train_lda, y_train)
y_pred_svm_lda = svm_lda.predict(X_test_lda)

accuracy_svm_lda = accuracy_score(y_test, y_pred_svm_lda)
precision_svm_lda = precision_score(y_test, y_pred_svm_lda, average="weighted", zero_division=0)
recall_svm_lda = recall_score(y_test, y_pred_svm_lda, average="weighted", zero_division=0)
f1_svm_lda = f1_score(y_test, y_pred_svm_lda, average="weighted", zero_division=0)

print(f"Accuracy : {accuracy_svm_lda:.4f}")
print(f"Precision: {precision_svm_lda:.4f}")
print(f"Recall   : {recall_svm_lda:.4f}")
print(f"F1-Score : {f1_svm_lda:.4f}")

# Calcula a matriz de confusão para visualizar acertos e confusões entre classes.
# Matriz de confusão: mostra os acertos e confusões entre as classes.
# CÉLULA 19 — MATRIZ SVM
cm_svm = confusion_matrix(y_test, y_pred_svm)
nomes_plot = [nomes_classes_pt[c] for c in encoder.classes_]

plt.figure(figsize=(10, 8))
sns.heatmap(cm_svm, annot=True, fmt="d", xticklabels=nomes_plot, yticklabels=nomes_plot)
plt.title("Matriz de Confusão — SVM + PCA")
plt.xlabel("Classe Predita")
plt.ylabel("Classe Real")
plt.xticks(rotation=45, ha="right")
plt.yticks(rotation=0)
plt.tight_layout()
plt.show()

# Camada convolucional responsável por extrair características espaciais das imagens.
# CÉLULA 20 — CNN
NUM_CLASSES = len(CLASSES_DESEJADAS)

cnn = keras.Sequential([
    layers.Input(shape=(64, 64, 3)),
    layers.Conv2D(32, (3,3), activation="relu"),
    layers.MaxPooling2D((2,2)),
    layers.Conv2D(64, (3,3), activation="relu"),
    layers.MaxPooling2D((2,2)),
    layers.Conv2D(128, (3,3), activation="relu"),
    layers.MaxPooling2D((2,2)),
    layers.Flatten(),
    layers.Dense(128, activation="relu"),
    layers.Dropout(0.5),
    layers.Dense(NUM_CLASSES, activation="softmax")
])

cnn.compile(optimizer="adam", loss="sparse_categorical_crossentropy", metrics=["accuracy"])
cnn.summary()

# Treinamento do modelo com os dados de treinamento.
# CÉLULA 21 — TREINAMENTO CNN
history = cnn.fit(
    X_train_img, y_train,
    validation_split=0.20,
    epochs=15,
    batch_size=32,
    verbose=1
)

# CÉLULA 22 — CURVAS CNN
plt.figure(figsize=(10,6))
plt.plot(history.history["accuracy"], label="Treino")
plt.plot(history.history["val_accuracy"], label="Validação")
plt.title("Acurácia durante o treinamento da CNN")
plt.xlabel("Época")
plt.ylabel("Acurácia")
plt.legend()
plt.tight_layout()
plt.show()

plt.figure(figsize=(10,6))
plt.plot(history.history["loss"], label="Treino")
plt.plot(history.history["val_loss"], label="Validação")
plt.title("Loss durante o treinamento da CNN")
plt.xlabel("Época")
plt.ylabel("Loss")
plt.legend()
plt.tight_layout()
plt.show()

# CÉLULA 23 — AVALIAÇÃO CNN
y_prob_cnn = cnn.predict(X_test_img, verbose=0)
y_pred_cnn = np.argmax(y_prob_cnn, axis=1)

accuracy_cnn = accuracy_score(y_test, y_pred_cnn)
precision_cnn = precision_score(y_test, y_pred_cnn, average="weighted", zero_division=0)
recall_cnn = recall_score(y_test, y_pred_cnn, average="weighted", zero_division=0)
f1_cnn = f1_score(y_test, y_pred_cnn, average="weighted", zero_division=0)

print(f"Accuracy : {accuracy_cnn:.4f}")
print(f"Precision: {precision_cnn:.4f}")
print(f"Recall   : {recall_cnn:.4f}")
print(f"F1-Score : {f1_cnn:.4f}")

print(classification_report(
    y_test, y_pred_cnn,
    target_names=nomes_plot,
    zero_division=0
))

# Calcula a matriz de confusão para visualizar acertos e confusões entre classes.
# Matriz de confusão: mostra os acertos e confusões entre as classes.
# CÉLULA 24 — MATRIZ CNN
cm_cnn = confusion_matrix(y_test, y_pred_cnn)

plt.figure(figsize=(10,8))
sns.heatmap(cm_cnn, annot=True, fmt="d", xticklabels=nomes_plot, yticklabels=nomes_plot)
plt.title("Matriz de Confusão — CNN")
plt.xlabel("Classe Predita")
plt.ylabel("Classe Real")
plt.xticks(rotation=45, ha="right")
plt.yticks(rotation=0)
plt.tight_layout()
plt.show()

# Calcula a curva ROC e a área sob a curva (AUC).
# Calcula e visualiza ROC/AUC para avaliar a separação entre as classes.
# CÉLULA 25 — ROC SVM
y_test_bin = label_binarize(y_test, classes=np.arange(NUM_CLASSES))
y_prob_svm = svm_pca.predict_proba(X_test_pca)

plt.figure(figsize=(10,8))
for i in range(NUM_CLASSES):
    fpr, tpr, _ = roc_curve(y_test_bin[:, i], y_prob_svm[:, i])
    roc_auc = auc(fpr, tpr)
    plt.plot(fpr, tpr, label=f"{nomes_plot[i]} (AUC={roc_auc:.2f})")

plt.plot([0,1], [0,1], linestyle="--", label="Aleatório")
plt.title("Curva ROC — SVM")
plt.xlabel("Taxa de Falsos Positivos")
plt.ylabel("Taxa de Verdadeiros Positivos")
plt.legend(bbox_to_anchor=(1.05,1), loc="upper left")
plt.tight_layout()
plt.show()

# Calcula a curva ROC e a área sob a curva (AUC).
# Calcula e visualiza ROC/AUC para avaliar a separação entre as classes.
# CÉLULA 26 — ROC CNN
plt.figure(figsize=(10,8))
for i in range(NUM_CLASSES):
    fpr, tpr, _ = roc_curve(y_test_bin[:, i], y_prob_cnn[:, i])
    roc_auc = auc(fpr, tpr)
    plt.plot(fpr, tpr, label=f"{nomes_plot[i]} (AUC={roc_auc:.2f})")

plt.plot([0,1], [0,1], linestyle="--", label="Aleatório")
plt.title("Curva ROC — CNN")
plt.xlabel("Taxa de Falsos Positivos")
plt.ylabel("Taxa de Verdadeiros Positivos")
plt.legend(bbox_to_anchor=(1.05,1), loc="upper left")
plt.tight_layout()
plt.show()

# CÉLULA 27 — COMPARAÇÃO
resultados = pd.DataFrame({
    "Modelo": ["SVM + PCA", "SVM + PCA + LDA", "CNN"],
    "Accuracy": [accuracy_svm, accuracy_svm_lda, accuracy_cnn],
    "Precision": [precision_svm, precision_svm_lda, precision_cnn],
    "Recall": [recall_svm, recall_svm_lda, recall_cnn],
    "F1-Score": [f1_svm, f1_svm_lda, f1_cnn]
})

display(resultados.round(4))

"""### 7. Comparação final
Os resultados dos modelos são reunidos para facilitar a comparação do desempenho no conjunto de teste.

"""

# CÉLULA 28 — GRÁFICO COMPARATIVO
resultados.set_index("Modelo").plot(kind="bar", figsize=(12,7))
plt.title("Comparação de desempenho dos modelos")
plt.xlabel("Modelo")
plt.ylabel("Valor da métrica")
plt.ylim(0,1)
plt.xticks(rotation=0)
plt.legend(title="Métrica")
plt.tight_layout()
plt.show()

# CÉLULA 29 — ANÁLISE DE ERROS
erros = np.where(y_pred_cnn != y_test)[0]
print("Total de erros:", len(erros))
print("Total de testes:", len(y_test))
print(f"Taxa de erro: {len(erros)/len(y_test)*100:.2f}%")

for classe_id in range(NUM_CLASSES):
    idx = np.where(y_test == classe_id)[0]
    erros_classe = np.sum(y_pred_cnn[idx] != classe_id)
    print(f"{nomes_plot[classe_id]}: {erros_classe} erros")

# CÉLULA 30 — VISUALIZAÇÃO DOS ERROS
if len(erros) > 0:
    qtd = min(12, len(erros))
    indices_erros = np.random.choice(erros, qtd, replace=False)
    plt.figure(figsize=(12,9))

    for pos, indice in enumerate(indices_erros):
        plt.subplot(3,4,pos+1)
        plt.imshow(X_test_img[indice])
        plt.title(
            f"Real: {nomes_plot[y_test[indice]]}\n"
            f"Predito: {nomes_plot[y_pred_cnn[indice]]}",
            fontsize=8
        )
        plt.axis("off")

    plt.tight_layout()
    plt.show()
else:
    print("Nenhum erro encontrado.")

# CÉLULA 31 — RESUMO FINAL
print("="*70)
print("RESUMO FINAL DO PROJETO")
print("="*70)
print("Dataset: PlantVillage — Hugging Face Streaming")
print("Classes:", NUM_CLASSES)
print("Imagens:", len(X))
print("Dimensão:", X.shape[1:])
print("Modelos: SVM + PCA, SVM + PCA + LDA e CNN")
print("\nSVM + PCA:", f1_svm)
print("SVM + PCA + LDA:", f1_svm_lda)
print("CNN:", f1_cnn)